---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jeromeRRRRR/ndcn-gitops.git
    targetRevision: HEAD
    path: infrastructure/metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system  # On le garde dans kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

