---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Replace=true,ServerSideApply=true
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.1
    helm:
      values: |
        grafana:
          adminPassword: "admin"
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              memory: "512Mi"
          readinessProbe:
            timeoutSeconds: 3
          livenessProbe:
            timeoutSeconds: 3
          service:
            type: ClusterIP
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
              disableMountSubPath: true
            resources:
              requests:
                cpu: "100m"
                memory: "400Mi"
              limits:
                memory: "800Mi"
        prometheus-node-exporter:
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 10
  syncPolicy:
    automated: # AJOUT DE CE BLOC
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - ServerSideApply=true
