---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    # On garde ces annotations car elles définissent le comportement de déploiement
    argocd.argoproj.io/sync-options: Replace=true,ServerSideApply=true
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.3.1
    helm:
      values: |
        grafana:
          adminPassword: "admin"
          # CORRECTIF GRAFANA : Sortie du mode BestEffort + Sondes assouplies
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              memory: "512Mi"
          readinessProbe:
            timeoutSeconds: 3
          livenessProbe:
            timeoutSeconds: 3
          service:
            type: ClusterIP

        prometheus:
          prometheusSpec:
            storageSpec:
              # CORRECTIF STORAGE : Défini à 2Gi pour valider le PVC
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
              disableMountSubPath: true # Crucial pour KIND sur Windows/WSL
            resources:
              requests:
                cpu: "100m"
                memory: "400Mi"
              limits:
                memory: "800Mi"

        # CORRECTIF NODE-EXPORTER : Augmentation des timeouts (Restart Storm)
        prometheus-node-exporter:
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 10
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    - ServerSideApply=true

