kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true  # Pour laisser Cilium gérer le réseau
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: /mnt/c/Users/jerom/Documents  # Chemin Windows vu par WSL
        containerPath: /var/data-shared  # Chemin à l'intérieur du nœud
  - role: worker
    extraMounts:
      - hostPath: /mnt/c/Users/jerom/Documents
        containerPath: /var/data-shared
