name: NDCN YAML Validation

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Optionnel : Force Node 24 pour toutes les actions (recommandé en 2026)
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5 # On passe en v5 pour éviter les warnings Node 20

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: "."
          config_data: |
            extends: default
            rules:
              line-length: disable
              document-start: disable

      - name: Kubeconform (Schema Validation)
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: "/kubeconform"
          # CORRECTION : On cible spécifiquement tes dossiers d'infrastructure
          # pour éviter que Kubeconform ne scanne le dossier .github/
          args: "-summary -ignore-missing-schemas apps/ certificates/ security/ infrastructure/"
