---
name: NDCN YAML Validation
"on": [push, pull_request]  # Utilise des guillemets pour le "on"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: "."
          config_data: |
            extends: default
            rules:
              line-length: disable
              document-start: disable  # Optionnel : désactive l'obligation du ---

      - name: Kubeconform (Schema Validation)
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: "/kubeconform"
          args: "-summary -ignore-filename-pattern .yaml -ignore-custom-resources ."
# Assure-toi d'avoir une ligne vide juste en dessous de cette ligne !
